version = 0.1
[default]
[default.pipeline_init]
[default.pipeline_init.parameters]
pipeline_user = "arn:aws:iam::660692570408:user/aws-sam-cli-managed-test-pipeline-res-PipelineUser-NB8ON4ORUBMY"

[test]
[test.pipeline_init]
[test.pipeline_init.parameters]
pipeline_execution_role = "arn:aws:iam::660692570408:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-EPMK81HAT4JF"
cloudformation_execution_role = "arn:aws:iam::660692570408:role/aws-sam-cli-managed-test-CloudFormationExecutionR-F84IA1M2SZPK"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-zmihng5ibexs"
region = "us-east-1"

[prod]
[prod.pipeline_init]
[prod.pipeline_init.parameters]
pipeline_execution_role = "arn:aws:iam::378812645829:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-662TD5SWMWWX"
cloudformation_execution_role = "arn:aws:iam::378812645829:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1A94GAEDR3QQ3"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1u13883vrwytt"
region = "us-west-2"
