version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::660692570408:user/aws-sam-cli-managed-test-pipeline-res-PipelineUser-5FXSHEII8WSH"

[test]
[test.pipeline_bootstrap]
[test.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::660692570408:role/aws-sam-cli-managed-test-pip-PipelineExecutionRole-1MNXD9TBFCXZ7"
cloudformation_execution_role = "arn:aws:iam::660692570408:role/aws-sam-cli-managed-test-CloudFormationExecutionR-1QX9PZXV4UYD8"
artifacts_bucket = "aws-sam-cli-managed-test-pipeline-artifactsbucket-8oryxbu3ouig"
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::660692570408:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1I7NK8VEGLE5Z"
cloudformation_execution_role = "arn:aws:iam::660692570408:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-TX76AK46Z9L5"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-3gsdj02auzku"
region = "us-west-2"
